// Conteúdo pedagógico de cada ano: palavras, peças (letras ou sílabas),
// figura, frase de leitura e "peças pegadinha" que se parecem com as certas.
const ANOS = {
  1: {
    titulo: '1º ano',
    subtitulo: 'Letras e setas',
    descricao: 'Forme palavras letra por letra, usando sequências de setas.',
    cor: '#ff8a3d',
    tamanho: 5,
    repetir: false,
    limiteBlocos: false,
    pedras: (n) => (n < 3 ? 0 : n < 6 ? 1 : 2),
    distratores: (n) => (n < 3 ? 1 : n < 6 ? 2 : 3),
    sobra: ['A', 'E', 'I', 'O', 'U', 'B', 'C', 'D', 'F', 'G', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'V'],
    palavras: [
      { palavra: 'SOL', pecas: ['S', 'O', 'L'], figura: '☀️' },
      { palavra: 'LUA', pecas: ['L', 'U', 'A'], figura: '🌙' },
      { palavra: 'UVA', pecas: ['U', 'V', 'A'], figura: '🍇' },
      { palavra: 'BOLA', pecas: ['B', 'O', 'L', 'A'], figura: '⚽' },
      { palavra: 'GATO', pecas: ['G', 'A', 'T', 'O'], figura: '🐱' },
      { palavra: 'PATO', pecas: ['P', 'A', 'T', 'O'], figura: '🦆' },
      { palavra: 'SAPO', pecas: ['S', 'A', 'P', 'O'], figura: '🐸' },
      { palavra: 'CASA', pecas: ['C', 'A', 'S', 'A'], figura: '🏠' },
      { palavra: 'VACA', pecas: ['V', 'A', 'C', 'A'], figura: '🐄' },
      { palavra: 'DADO', pecas: ['D', 'A', 'D', 'O'], figura: '🎲' },
    ],
  },
  2: {
    titulo: '2º ano',
    subtitulo: 'Sílabas e repetição',
    descricao: 'Junte sílabas para formar palavras e use o bloco REPETIR.',
    cor: '#2bb673',
    tamanho: 6,
    repetir: true,
    limiteBlocos: false,
    pedras: (n) => (n < 3 ? 2 : n < 6 ? 3 : 5),
    distratores: (n) => (n < 3 ? 2 : n < 6 ? 3 : 4),
    sobra: ['BA', 'BE', 'DO', 'FI', 'GU', 'JU', 'LI', 'MO', 'NU', 'PE', 'RI', 'SU', 'TU', 'VE', 'ZO'],
    palavras: [
      { palavra: 'BOLO', pecas: ['BO', 'LO'], figura: '🎂', frase: 'O bolo de festa é gostoso.' },
      { palavra: 'PIPOCA', pecas: ['PI', 'PO', 'CA'], figura: '🍿', frase: 'A pipoca pula na panela.' },
      { palavra: 'BONECA', pecas: ['BO', 'NE', 'CA'], figura: '🪆', frase: 'A boneca tem um vestido azul.' },
      { palavra: 'MACACO', pecas: ['MA', 'CA', 'CO'], figura: '🐒', frase: 'O macaco come banana no galho.' },
      { palavra: 'CAVALO', pecas: ['CA', 'VA', 'LO'], figura: '🐴', frase: 'O cavalo corre no campo.' },
      { palavra: 'SAPATO', pecas: ['SA', 'PA', 'TO'], figura: '👞', frase: 'Meu sapato novo é marrom.' },
      { palavra: 'TOMATE', pecas: ['TO', 'MA', 'TE'], figura: '🍅', frase: 'O tomate maduro é vermelho.' },
      { palavra: 'BANANA', pecas: ['BA', 'NA', 'NA'], figura: '🍌', frase: 'A banana é amarela e doce.' },
      { palavra: 'GIRAFA', pecas: ['GI', 'RA', 'FA'], figura: '🦒', frase: 'A girafa tem o pescoço comprido.' },
      { palavra: 'PETECA', pecas: ['PE', 'TE', 'CA'], figura: '🏸', frase: 'Vamos jogar peteca no recreio?' },
    ],
  },
  3: {
    titulo: '3º ano',
    subtitulo: 'Sílabas complexas e desafio',
    descricao: 'Encare dígrafos e sílabas difíceis com poucos blocos!',
    cor: '#7b61ff',
    tamanho: 7,
    repetir: true,
    limiteBlocos: true,
    pedras: (n) => (n < 3 ? 4 : n < 6 ? 6 : 8),
    distratores: (n) => (n < 3 ? 3 : n < 6 ? 4 : 5),
    sobra: ['XA', 'CHE', 'LA', 'NA', 'RO', 'SA', 'GE', 'QUA', 'PRA', 'BLE'],
    palavras: [
      { palavra: 'CHUVA', pecas: ['CHU', 'VA'], figura: '🌧️', armadilhas: ['XU', 'CU'], frase: 'A chuva molhou o quintal.' },
      { palavra: 'QUEIJO', pecas: ['QUEI', 'JO'], figura: '🧀', armadilhas: ['KEI', 'GO'], frase: 'O rato adora queijo.' },
      { palavra: 'BRUXA', pecas: ['BRU', 'XA'], figura: '🧙', armadilhas: ['BUR', 'CHA'], frase: 'A bruxa voa na vassoura.' },
      { palavra: 'GALINHA', pecas: ['GA', 'LI', 'NHA'], figura: '🐔', armadilhas: ['NA', 'LHA'], frase: 'A galinha botou um ovo.' },
      { palavra: 'PALHAÇO', pecas: ['PA', 'LHA', 'ÇO'], figura: '🤡', armadilhas: ['LA', 'SO'], frase: 'O palhaço faz a plateia rir.' },
      { palavra: 'CACHORRO', pecas: ['CA', 'CHOR', 'RO'], figura: '🐶', armadilhas: ['XOR', 'CHO'], frase: 'O cachorro late para o carteiro.' },
      { palavra: 'PÁSSARO', pecas: ['PÁS', 'SA', 'RO'], figura: '🐦', armadilhas: ['PA', 'ÇA'], frase: 'O pássaro canta de manhã.' },
      { palavra: 'ESTRELA', pecas: ['ES', 'TRE', 'LA'], figura: '⭐', armadilhas: ['TER', 'IS'], frase: 'A estrela brilha no céu.' },
      { palavra: 'GUITARRA', pecas: ['GUI', 'TAR', 'RA'], figura: '🎸', armadilhas: ['GI', 'TRA'], frase: 'Ele toca guitarra na banda.' },
      { palavra: 'BORBOLETA', pecas: ['BOR', 'BO', 'LE', 'TA'], figura: '🦋', armadilhas: ['BRO', 'LHE'], frase: 'A borboleta pousou na flor.' },
    ],
  },
};

if (typeof module !== 'undefined') module.exports = { ANOS };
